### ISSUE TITLE
Maintaining state between questions

### ISSUE THREAD

**Issue by kevindewalt** [prolego-team/neo-sophia#68]
I've noticed that the SQLite chat demo doesn't seem to maintain state between chats like ChatGPT. Is this as possible enhancement?

**Comment by jmpounders** [comment]
Yes.  There is a quick, easy and inefficient/high-latency method I could put in anytime.  There's also a better way to do it in the medium term that would be a bit of work.

**Comment by kevindewalt** [comment]
Ok. I figured it was a performance tradeoff. Perfect.
