### ISSUE TITLE
Expand answer field length

### ISSUE THREAD

**Issue by kevindewalt** [prolego-team/neo-sophia#89]
<img width="2498" alt="Screen Shot 2023-08-14 at 10 05 18 AM" src="https://github.com/prolego-team/neo-sophia/assets/52680/16e6cc6e-9423-4242-931a-cbce9aa0f9e0">

<img width="2397" alt="Screen Shot 2023-08-14 at 10 06 12 AM" src="https://github.com/prolego-team/neo-sophia/assets/52680/c0685838-089d-4558-aca6-ad0720b8602c">

**Comment by jmpounders** [comment]
Added fix to #86
